server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #是否向注册中心注册
    register-with-eureka: false
    #注册中心用false
    fetch-registry: false
    service-url:
      #集群指向其它eureka
#      defaultZone: http://eureka7002.com:7002/eureka/
#      单机, 需要配置host 127.0.0.1     eureka7001.com
      defaultZone: http://eureka7001.com:7001/eureka/
#      单机
#      defaultZone: http://localhost:7001/eureka/
#    server:
    #关闭自我保护机制，保证不可用服务被及时踢除
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 2000