
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否从注册中心动态创建路由
          enabled: true
      routes:
        #路由ID，没有固定规则但要求唯一，配合服务名
        #==============cloud-payment-service==============
        - id: cloud-payment-service
          #匹配后路由的地址，使用微服务服务名 spring.application.name 或者使用 uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
          #- Path  路径匹配才进行路由，匹配 /payment/get/** 和 /payment/discovery/**
          - Path=/payment/get/**,/payment/discovery/**
          #==============baidu_route==============
#        - id: baidu_route
#          uri: http://news.baidu.com/guonei
#          predicates:
#          - Path=/guonei

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
#      host配置: 127.0.0.1     eureka7001.com
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://localhost:7001/eureka


